### ISSUE TITLE
UnknownMethod error in portal on XFCE

### ISSUE THREAD

**Issue by TechnicJelle** [FineFindus/eyedropper#151]
**Describe the bug**
I just heard about this program, and it seems to be exactly what I've been looking for!
So I installed it just now, from the [AUR](https://aur.archlinux.org/packages/eyedropper) and started it up.
But it says "Failed to pick a color" in a popup toast message.
In the console, it's saying this:
```
ERROR eyedropper::window > ZBus Error: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop
```

I already checked for similar issues, and found #6, #63, and #72, but no solution in there worked for me.
I'm on Manjaro XFCE (so X11), and I do have some xdg portals installed:
```bash
$ pacman -Q | grep portal
libportal 0.7.1-2
libportal-gtk3 0.7.1-2
xdg-desktop-portal 1.18.4-1
xdg-desktop-portal-gtk 1.15.1-2
```
Or do I specifically need the gnome one, instead of (or in addition to?) the gtk one?

I can successfully press Ctrl+R to get a random colour, though.

<details>
  <summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/ed1c31d6-4327-4e5e-b70b-6f8d2c8a1e51)
![image](https://github.com/user-attachments/assets/064fcb1f-c573-4fe6-b295-027f5deaf78e)
![image](https://github.com/user-attachments/assets/68ee8f68-5a3d-4e5b-ab45-770510928d61)
(The colours on the right are all the same dark background colour. Is that a bug as well? Should I report this in a new, separate issue?)

Possibly useful system info:
![image](https://github.com/user-attachments/assets/2a130e07-86d9-4c4e-a1f0-c4c79b93772e)

</details>

**Information**

<details>
  <summary>Debugging Information</summary>

```
Eyedropper: 1.0.0
Profile: 
Backend: X11
OS:
 - Name: "Manjaro Linux"
 - Version: "Failed to get VERSION"
Libraries:
 - GTK: 4.14.4
 - Libadwaita: 1.5.1

Sandbox:  - GTK_USE_PORTAL: false


Portal error: Some(Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.39"))), reply-serial: 5, body: Signature("s") })))

```

</details>
